"""Compatibility shim for moved shared models."""

from jira2ai_core.models import (
    AttachmentMeta,
    CommentPage,
    FieldMeta,
    FieldSchema,
    IssueFields,
    IssueLink,
    IssueLinkType,
    IssueRef,
    IssueType,
    JiraComment,
    JiraIssue,
    JiraModel,
    JiraProject,
    JiraUser,
    LinkedIssue,
    LinkedIssueFields,
    NamedResource,
    ProjectSearchResult,
    SearchResult,
    Subtask,
    SubtaskFields,
    user_display,
)

__all__ = [
    "AttachmentMeta",
    "CommentPage",
    "FieldMeta",
    "FieldSchema",
    "IssueFields",
    "IssueLink",
    "IssueLinkType",
    "IssueRef",
    "IssueType",
    "JiraComment",
    "JiraIssue",
    "JiraModel",
    "JiraProject",
    "JiraUser",
    "LinkedIssue",
    "LinkedIssueFields",
    "NamedResource",
    "ProjectSearchResult",
    "SearchResult",
    "Subtask",
    "SubtaskFields",
    "user_display",
]
